spring.application.name=servicedesk-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/servicedesk_db
spring.datasource.username=postgres
spring.datasource.password=indra

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=servicedesk-pro-development-secret-key-please-change-this
jwt.expiration=3600000